version: 0.2

phases:
  build:
    commands:
      - echo Preparing files for deployment

artifacts:
  files:
    - '**/*'
  exclude-paths:
    - 'buildspec.yml'
    - 'deploytos3.yml'
    - '.git/**/*'
